spring:
  application:
    name: day
  datasource:
    url: ${SUPABASE_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: app